plugins:
  topic_priority_enabled:
    default: true
    client: true
  topic_priority_field_name:
    default: 'priority'
    client: true
    hidden: true
  topic_priority_field_type:
    default: 'integer'
    client: true
    hidden: true
  topic_priority_field_categories:
    default: []
    client: true
    type: list
    list_type: category
    description: "Categories where the priority is enabled."
  topic_priority_field_allowed_groups:
    default: "staff"
    client: true
    type: list
    list_type: group
    description: "Groups that are allowed to edit the priority."