plugins:
  topic_custom_field_enabled:
    default: true
    client: true
  topic_custom_field_name:
    default: 'price'
    client: true
  topic_custom_field_type:
    default: 'integer'
    client: true
    type: enum
    choices:
      - string
      - integer
      - boolean
      - json
  topic_custom_field_categories:
    default: []
    client: true
    type: list
    list_type: category
    description: "Categories where the custom field is enabled."
  topic_custom_field_allowed_groups:
    default: "staff"
    client: true
    type: list
    list_type: group
    description: "Groups that are allowed to edit the custom field value."